In [9]:
pip install pandas
pip install numpy
pip install scikit-learn

SyntaxError: invalid syntax (4052763064.py, line 1)

In [ ]:
import kagglehub
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

Step 1 - Downloading Data Set

In [ ]:
path = kagglehub.dataset_download("gregorut/videogamesales")

print("Path to dataset files:", path)

importing dataset

In [11]:
file_path = 'vgsales.csv'

display first five rows

In [28]:
df = pd.read_csv(file_path)
print(f"--- dataset imported successfully {df.shape} ---")
display(df.head())

--- dataset imported successfully (16598, 11) ---

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

Task 1 - checking and filling missing values

In [29]:
num_cols = df.select_dtypes(include=[np.number]).columns #taking only numbers values
print("the missing values before processing for each column are:")
print(df[num_cols].isnull().sum())

#filling missing columns
for col in num_cols:
    if df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)
        print(f"Filled column '{col}' with median: {median_val}")

print("\n the missing values after processing for each column are:")
print(df[num_cols].isnull().sum())

the missing values before processing for each column are:
Rank              0
Year            271
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64
Filled column 'Year' with median: 2007.0

 the missing values after processing for each column are:
Rank            0
Year            0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

Task 2 - removing duplicated rows

In [32]:
duplicates_count = df.duplicated().sum() # gets counts of duplicated rows
print(f"number of dublicated rows before deleting are: {duplicates_count}")

df = df.drop_duplicates().reset_index(drop=True) # removing duplicated rows
print(f"number of dublicated rows after deleting are: {df.duplicated().sum()}")

number of dublicated rows before deleting are: 0
number of dublicated rows after deleting are: 0

Task 3 - Applying Label Encoding to a single categorical column

In [37]:
target_cat_col = 'Genre' # picking game Genre column

le = LabelEncoder()

df[target_cat_col] = df[target_cat_col].fillna('Unknown') # filling missing values, because it makes errors

df[target_cat_col + '_Encoded'] = le.fit_transform(df[target_cat_col]) # applying transform + making a new column for it

print(f"Label Encoding successfully applied to column: '{target_cat_col}'")

# showing data before and after lable encoding
display(df[[target_cat_col, target_cat_col + '_Encoded']].head(10))

Label Encoding successfully applied to column: 'Genre'

          Genre  Genre_Encoded
0        Sports             10
1      Platform              4
2        Racing              6
3        Sports             10
4  Role-Playing              7
5        Puzzle              5
6      Platform              4
7          Misc              3
8      Platform              4
9       Shooter              8